version: '3'
services:
  postgres:
    image: postgres:13.3
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    expose:
      - 5432

  django:
    build: ./django
    env_file:
      - ./.env
    volumes:
      - static:/movies_admin/.venv/static
    depends_on:
      - postgres
    expose:
      - 8000

  nginx:
    build: ./nginx
    env_file:
      - ./.env
    volumes:
      - static:/data/static
    depends_on:
      - django
      - postgres
    ports:
      - "8080:80"

volumes:
  pgdata:
  static:
