version: '3'
services:
  postgres:
    image: postgres:13.3
    env_file:
      - ./.env
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/
    ports:
      - "8432:5432"

  migrations:
    build: ./django
    command: python manage.py migrate --noinput
    env_file:
      - ./.env
    depends_on:
      - postgres

  django:
    build: ./django
    env_file:
      - ./.env
    depends_on:
      - postgres
      - migrations
    expose:
      - "8000"

  nginx:
    image: nginx:1.24
    env_file:
      - ./.env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - ./django/app/static:/data/static:ro
    depends_on:
      - django
      - postgres
    ports:
      - "8080:80"
