# Generated by Django 3.2 on 2023-09-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="personfilmwork",
            name="unique_person_filmwork",
        ),
        migrations.RenameField(
            model_name="filmwork",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="filmwork",
            old_name="modified",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="genre",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="genre",
            old_name="modified",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="genrefilmwork",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="modified",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="personfilmwork",
            old_name="created",
            new_name="created_at",
        ),
        migrations.AddConstraint(
            model_name="genrefilmwork",
            constraint=models.UniqueConstraint(
                fields=("film_work_id", "genre_id"), name="film_work_genre"
            ),
        ),
        migrations.AddConstraint(
            model_name="personfilmwork",
            constraint=models.UniqueConstraint(
                fields=("film_work_id", "person_id", "role"),
                name="film_work_person_role",
            ),
        ),
    ]
