# Generated by Django 3.2 on 2023-09-12 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_auto_20230911_1945"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filmwork",
            name="creation_date",
            field=models.DateField(
                db_index=True, null=True, verbose_name="creation_date"
            ),
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="description",
            field=models.TextField(null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="filmwork",
            name="rating",
            field=models.FloatField(
                db_index=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="rating",
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="description",
            field=models.TextField(null=True, verbose_name="description"),
        ),
    ]
