# Generated by Django 4.2.5 on 2023-10-12 16:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0005_alter_filmwork_options_alter_genre_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genrefilmwork",
            options={
                "verbose_name": "Filmwork Genre",
                "verbose_name_plural": "Filmwork Genres",
            },
        ),
        migrations.AlterModelOptions(
            name="personfilmwork",
            options={
                "verbose_name": "Filmwork Person",
                "verbose_name_plural": "Filmwork Persons",
            },
        ),
    ]
