# Generated by Django 4.2.5 on 2023-10-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0006_alter_genrefilmwork_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filmwork",
            name="persons",
            field=models.ManyToManyField(
                through="movies.PersonFilmwork",
                to="movies.person",
                verbose_name="persons",
            ),
        ),
    ]
