# Generated by Django 3.2.21 on 2023-09-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_auto_20230912_1922"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personfilmwork",
            name="role",
            field=models.CharField(
                choices=[
                    ("actor", "actor"),
                    ("writer", "writer"),
                    ("director", "director"),
                ],
                default="actor",
                max_length=8,
                verbose_name="role",
            ),
        ),
    ]
